#!/bin/bash

# Check current owner of hello
current_owner=$(stat -c '%U' hello)

# If current owner is guillaume, change owner to betty
if [ "$current_owner" = "guillaume" ]; then
    sudo chown betty hello
fi